{{- if .Values.enabled -}}
{{- $nginxConfigmapName := include "nginx-configmap.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $nginxConfigmapName }}
data:
  geoserver-location.conf: {{ tpl (.Files.Get "config/geoserver-location.conf") . | quote }}
  geoserver-server.conf: {{ tpl (.Files.Get "config/geoserver-server.conf") . | quote }}
{{- end }}
