{{- if .Values.enabled -}}
{{- $nginxConfigmapName := include "nginx-configmap.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $nginxConfigmapName }}
data:
  geoserver.conf: {{ tpl (.Files.Get "config/geoserver.conf") . | quote }}
{{- end }}
