{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "route.fullname" . }}
spec:
  path:  {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ template "geoserver.fullname" . }}
  {{ if .Values.route.tls }}
  tls:
    termination: edge
  {{ end }}
{{- end -}}
