{{- $geoserver := (include "common.geoserver.merged" .) | fromYaml }}
{{- if $geoserver.secrets.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.fullname" . }}
  labels:
{{ include "geoserver.labels" . | indent 4 }}
type: Opaque
data:
  GEOSERVER_USER: {{ $geoserver.auth.username | b64enc | quote }}
  GEOSERVER_PASS: {{ $geoserver.auth.password | b64enc | quote }}
{{- end -}}  
