apiVersion: v1
kind: Secret
metadata:
  name: {{ template "geoserver.secretName" . }}
  labels:
{{ include "geoserver.labels" . | indent 4 }}
type: Opaque
data:
  GEOSERVER_USER: {{ .Values.geoserverUser | b64enc | quote }}
  GEOSERVER_PASS: {{ .Values.geoserverPassword | b64enc | quote }}
