apiVersion: v1
kind: Service
metadata:
  name: {{ template "geoserver.fullname" . }}
  labels:
{{ include "geoserver.labels" . | indent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-geoserver
      port: 80
      protocol: TCP
      targetPort: http-geoserver
  selector:
{{ include "geoserver.selectorLabels" . | indent 4 }}
