apiVersion: v2
name: pp-geoserver
type: application
version: 3.0.0
appVersion: 3.0.0
description: Chart for geoserver in openshift
dependencies:
  - name: nginx
    version: 2.1.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
    condition: enabled
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
